Практическая работа

In [ ]:
train_test_split - она делит данные на обучающую и тестовую выборки
StandardScaler — он приводит числовые признаки к одному масштабу

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

df только те столбцы, которые будут признаками модели:

In [4]:
X = df[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch"]]
X.head()

   Pclass   Age     Sex     Fare  SibSp  Parch
0       3  22.0    male   7.2500      1      0
1       1  38.0  female  71.2833      1      0
2       3  26.0  female   7.9250      0      0
3       1  35.0  female  53.1000      1      0
4       3  35.0    male   8.0500      0      0

Survived как целевую переменную. именно её модель должна научиться предсказывать: 0 - пассажир не выжил, 1 - выжил

In [19]:
y = df["Survived"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

isnull() возвращает таблицу True/False (где True - пропуск NaN), а .sum() складывает True по каждому столбцу. Получаем количество пропусков в каждой колонке

In [5]:
X.isnull().sum()

Pclass      0
Age       177
Sex         0
Fare        0
SibSp       0
Parch       0
dtype: int64

In [8]:
X = df[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch"]].copy()

map({...}) заменяет каждое текстовое значение по словарю: "male" - 0, "female" - 1

In [9]:
X.loc[:, "Sex"] = X["Sex"].map({
    "male": 0,
    "female": 1
})
X.head()

   Pclass   Age Sex     Fare  SibSp  Parch
0       3  22.0   0   7.2500      1      0
1       1  38.0   1  71.2833      1      0
2       3  26.0   1   7.9250      0      0
3       1  35.0   1  53.1000      1      0
4       3  35.0   0   8.0500      0      0

In [10]:
X.info()
print("\nПропуски:")
print(X.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Age     714 non-null    float64
 2   Sex     891 non-null    object
 3   Fare    891 non-null    float64
 4   SibSp   891 non-null    int64
 5   Parch   891 non-null    int64
dtypes: float64(2), int64(3), object(1)
memory usage: 41.9+ KB

Пропуски:
Pclass      0
Age       177
Sex         0
Fare        0
SibSp       0
Parch       0
dtype: int64

X_train, y_train - обучающая выборка, 
X_test, y_test - тестовая выборка,
test_size=0.2 - 20% данных идёт в тест, 80% - в обучение.
Random_state=42 - фиксируем случайность, чтобы результат был воспроизводимым

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

fit_transform делает два действия сразу:
fit - по обучающим данным вычисляет среднее и стандартное отклонение каждого признака;
transform - применяет преобразование: (x - mean) / std

In [20]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [21]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (712, 6)
X_test: (179, 6)
y_train: (712,)
y_test: (179,)